language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
- pypy3
install:
- pip install -e .
- pip install pytest pytest-cov coveralls
script:
- py.test -v --cov=trueskill
after_success:
- coveralls
